// This file was auto-generated by prisma-generator-typescript-interfaces

export type Status = "ACTIVE" | "INACTIVE";

export type LogActionType = "CREATE" | "UPDATE" | "DELETE";

export type CustomerType = "INDIVIDUAL" | "COMPANY";

export type VerificationType = "EMAIL" | "PHONE";

export type MapType = "LAND" | "APARTMENT";

export type PropertyStatus = "NOT_SELLABLE" | "AVAILABLE";

export type ApplicationStatus = "NEW" | "PENDING" | "ON_HOLD" | "CANCELLED" | "PURCHASED";

export type TransactionStatus = "PENDING" | "APPROVED" | "DECLINED";

export type MeetingStatus = "PENDING" | "DONE";

export type InvoiceType = "OWNER" | "GOVERNMENT" | "GATEWAY";

export type SiteContentProjectStatus = "ON_SALE" | "SOLD_OUT" | "COMING_SOON";

export interface User {
  id: string;
  number: string;
  name: string | null;
  email: string;
  picture: string | null;
  phone: string;
  isPhoneVerified: boolean;
  password: string | null;
  designation: string | null;
  department: string | null;
  workPhone: string | null;
  workEmail: string | null;
  workAddress: string | null;
  bankAccount: string | null;
  dateOfBirth: Date | null;
  otp: string | null;
  otpExpiredAt: Date | null;
  contract: UserContract | null;
  documents: string[];
  hasContentEditAccess: boolean;
  status: Status;
  placeInHierarchy: string;
  isDeleted: boolean;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  projects?: Project[];
  maps?: Map[];
  lands?: Land[];
  apartments?: Apartment[];
  applications?: Application[];
  applicationReminders?: ApplicationReminder[];
  customerReminders?: CustomerReminder[];
  changeLogs?: ChangeLog[];
  notifications?: Notification[];
  userExperiences?: UserExperience[];
  userQualifications?: UserQualification[];
  userFamily?: UserFamily[];
  Referral?: Referral[];
  Customer?: Customer[];
  Transaction?: Transaction[];
  SiteContentProject?: SiteContentProject[];
}

export interface UserExperience {
  id: string;
  user?: User;
  userId: string;
  title: string;
  company: string;
  location: string;
  startDate: Date;
  endDate: Date | null;
  description: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface UserQualification {
  id: string;
  user?: User;
  userId: string;
  title: string;
  institute: string;
  location: string;
  startDate: Date;
  endDate: Date | null;
  description: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface UserFamily {
  id: string;
  user?: User;
  userId: string;
  name: string;
  relation: string;
  dateOfBirth: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface ChangeLog {
  id: string;
  userId: string;
  user?: User;
  url: string;
  description: LocalizedValue;
  createdAt: Date;
}

export interface Notification {
  id: string;
  title: string;
  description: string;
  type: string;
  user?: User;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Customer {
  id: string;
  number: string;
  name: string | null;
  email: string;
  isEmailVerified: boolean;
  picture: string | null;
  address: string | null;
  city: string | null;
  country: string | null;
  zipCode: string | null;
  phone: string;
  isPhoneVerified: boolean;
  password: string | null;
  company: string | null;
  type: CustomerType;
  tags: string[];
  language: string | null;
  otp: string | null;
  otpExpiredAt: Date | null;
  website: string | null;
  taxNumber: string | null;
  idNumber: string | null;
  nationality: string | null;
  notes: string | null;
  bankingDetails: BankingDetails | null;
  isDeleted: boolean;
  deletedAt: Date | null;
  updatedBy?: User | null;
  updatedById: string | null;
  status: Status;
  isSeller: boolean;
  createdAt: Date;
  updatedAt: Date;
  verifications?: Verification[];
  ownerships?: Ownership[];
  applications?: Application[];
  customerReminders?: CustomerReminder[];
  invoices?: Invoice[];
  transactions?: Transaction[];
}

export interface CustomerReminder {
  id: string;
  customer?: Customer;
  customerId: string;
  title: string;
  description: string;
  reminderAt: Date;
  isDone: boolean;
  user?: User;
  userId: string;
  files: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Verification {
  id: string;
  customer?: Customer;
  customerId: string;
  type: VerificationType;
  otp: string;
  expiredAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface Referral {
  id: string;
  number: string;
  name: string | null;
  expiredAt: Date | null;
  createdBy?: User;
  createdById: string;
  isDeleted: boolean;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  referralAnalytics?: ReferralAnalytics[];
}

export interface ReferralAnalytics {
  id: string;
  referral?: Referral;
  referralId: string;
  ipAddress: string;
  browser: string;
  os: string;
  language: string;
  country: string;
  region: string;
  city: string;
  screenResolution: string;
  timezone: string;
  cookiesEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Analytics {
  id: string;
  path: string;
  ipAddress: string;
  browser: string;
  os: string;
  language: string;
  country: string;
  region: string;
  city: string;
  screenResolution: string;
  timezone: string;
  cookiesEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Project {
  id: string;
  number: string;
  name: LocalizedValue | null;
  area: string | null;
  city: LocalizedValue | null;
  description: LocalizedValue | null;
  timeline: string | null;
  primaryColor: string | null;
  secondaryColor: string | null;
  logo: LocalizedValue | null;
  logoIcon: string | null;
  banner: string | null;
  visible: boolean;
  user?: User;
  userId: string;
  isDeleted: boolean;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  maps?: Map[];
  lands?: Land[];
  apartments?: Apartment[];
  applications?: Application[];
  Asset3d?: Asset3d[];
}

export interface Asset3d {
  id: string;
  number: string;
  project?: Project;
  projectId: string;
  name: LocalizedValue | null;
  files: string[];
  link360: string | null;
  createdAt: Date;
  updatedAt: Date;
  Apartment?: Apartment[];
}

export interface Map {
  id: string;
  project?: Project;
  projectId: string;
  number: string;
  name: LocalizedValue | null;
  area: number | null;
  description: LocalizedValue | null;
  logoIcon: string | null;
  backgroundImage: string | null;
  backgroundImageMobile: string | null;
  type: MapType;
  geoJson: string | null;
  model: string | null;
  latitude: number | null;
  longitude: number | null;
  dayStills: string[];
  nightStills: string[];
  user?: User;
  userId: string;
  tokenPrice: number | null;
  visible: boolean;
  isDeleted: boolean;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  lands?: Land[];
  apartments?: Apartment[];
  applications?: Application[];
  developments?: MapDevelopment[];
}

export interface MapDevelopment {
  id: string;
  title: string;
  description: string;
  files: string[];
  isDone: boolean;
  startedAt: Date | null;
  expectedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  Map?: Map | null;
  mapId: string | null;
}

export interface Ownership {
  id: string;
  owner?: Customer | null;
  ownerId: string | null;
  ownerByName: string | null;
  unitPrice: number | null;
  status: PropertyStatus;
  apartment?: Apartment | null;
  apartmentId: string | null;
  land?: Land | null;
  landId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Apartment {
  id: string;
  number: string;
  project?: Project;
  projectId: string;
  map?: Map;
  mapId: string;
  images: string[];
  pdfs: string[];
  tower: string;
  floor: string;
  unit: string;
  unitType: LocalizedValue | null;
  area: number | null;
  balconyArea: number | null;
  roofArea: number | null;
  parkingArea: number | null;
  unitAreaWithAttachments: number | null;
  numberOfBedrooms: number | null;
  numberOfBathrooms: number | null;
  numberOfGardens: number | null;
  numberOfBalconies: number | null;
  numberOfParking: number | null;
  unitShareOfLand: number | null;
  unitShareOfCommonArea: number | null;
  notes: string | null;
  user?: User;
  userId: string;
  owners?: Ownership[];
  asset3d?: Asset3d | null;
  asset3dId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Land {
  id: string;
  number: string;
  project?: Project;
  projectId: string;
  map?: Map;
  mapId: string;
  plot: string;
  dimensions: string | null;
  images: string[];
  pdfs: string[];
  mapLink: string | null;
  area: number | null;
  block: string | null;
  orientation: LocalizedValue | null;
  purpose: LocalizedValue | null;
  unitType: LocalizedValue | null;
  lengths: Lenghts;
  roadWidths: number[];
  nearByFacilitiesDistance: NearByFacilitiesDistance;
  user?: User;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
  owners?: Ownership[];
}

export interface Application {
  id: string;
  number: string;
  customer?: Customer;
  customerId: string;
  project?: Project;
  projectId: string;
  map?: Map;
  mapId: string;
  status: ApplicationStatus;
  reasonForCancellation: string | null;
  message: string | null;
  actionBy?: User | null;
  actionById: string | null;
  firstActionAt: Date | null;
  lastActionAt: Date | null;
  purchaseAt: Date | null;
  amount: number;
  purchaseNote: string | null;
  gatewayTransactionId: string | null;
  gatewayTransactionAmount: number | null;
  gatewayTransactionAt: Date | null;
  gatewayTransactionStatus: TransactionStatus | null;
  reservedTill: Date | null;
  meetingAt: Date | null;
  meetingNote: string | null;
  meetingLocation: string | null;
  meetingStatus: MeetingStatus | null;
  isDeleted: boolean;
  deletedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  applicationReminders?: ApplicationReminder[];
  applicationSelected?: ApplicationSelected[];
  invoices?: Invoice[];
}

export interface ApplicationSelected {
  id: string;
  propertyType: string;
  propertyId: string;
  files: string[];
  createdAt: Date;
  updatedAt: Date;
  application?: Application | null;
  applicationId: string | null;
}

export interface ApplicationReminder {
  id: string;
  application?: Application;
  applicationId: string;
  title: string;
  description: string;
  reminderAt: Date;
  isDone: boolean;
  user?: User;
  userId: string;
  files: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Invoice {
  id: string;
  number: string;
  customer?: Customer;
  customerId: string;
  application?: Application;
  applicationId: string;
  properties: InvoiceProperty[];
  amount: number;
  dueAt: Date;
  paidAt: Date | null;
  paidAmount: number;
  type: InvoiceType;
  viewedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  transactions?: Transaction[];
}

export interface Transaction {
  id: string;
  number: string;
  customer?: Customer;
  customerId: string;
  invoice?: Invoice;
  invoiceId: string;
  propertyId: string | null;
  amount: number;
  status: TransactionStatus;
  reasonForDecline: string | null;
  file: string | null;
  actionBy?: User | null;
  actionById: string | null;
  showTo: string[];
  actionAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface Interest {
  id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  interest: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface MarketingInterest {
  id: string;
  name: string | null;
  phone: string | null;
  email: string | null;
  sex: string | null;
  city: string | null;
  specialty: string | null;
  bio: string | null;
  hasLicense: boolean | null;
  license: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface NewsLetter {
  id: string;
  email: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CallScheduled {
  id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  timeSlot: string | null;
  preferredContactMethod: string | null;
  isDone: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface QrScanned {
  id: string;
  value: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface SiteContentProject {
  id: string;
  number: string;
  name: LocalizedValue | null;
  logo: LocalizedValue | null;
  description: LocalizedValue | null;
  city: LocalizedValue | null;
  area: number;
  numberOfEntity: number | null;
  nameOfEntity: LocalizedValue | null;
  banner: string | null;
  picture: string | null;
  slides: string[];
  status: SiteContentProjectStatus;
  visible: boolean;
  actionBy?: User;
  actionById: string;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface UserContract {
  salary: number;
  startDate: Date;
  endDate: Date | null;
  wage: number;
  houseAllowance: number;
  transportAllowance: number;
  otherAllowance: number;
  otherDeduction: number;
}

export interface BankingDetails {
  inUse: boolean;
  bankName: string;
  iban: string;
}

export interface LocalizedValue {
  en: string | null;
  ar: string | null;
}

export interface NearByFacilitiesDistance {
  university: number | null;
  highSchool: number | null;
  elementarySchool: number | null;
  mosque: number | null;
  publicPark: number | null;
  healthCenter: number | null;
  hospital: number | null;
  shoppingCenter: number | null;
  culturalCenter: number | null;
  museum: number | null;
  library: number | null;
  sportHall: number | null;
  playground: number | null;
  publicRestaurant: number | null;
  socialCenter: number | null;
  artsAndTheaterCenter: number | null;
  publicTransportation: number | null;
  trainingCenter: number | null;
  childrenPlayArea: number | null;
  elderlyCenter: number | null;
  commercialMarket: number | null;
  waterSportFacility: number | null;
  petCareCenter: number | null;
  policeStation: number | null;
  fireStation: number | null;
  ambulanceStation: number | null;
  immigrationOffice: number | null;
  civilRegistryOffice: number | null;
}

export interface Lenghts {
  north: number | null;
  south: number | null;
  east: number | null;
  west: number | null;
}

export interface InvoiceProperty {
  propertyId: string;
  amount: number;
}
